CREATE DATABASE SENAI_ROMAN_DESAFIO_SIESG;

USE SENAI_ROMAN_DESAFIO_SIESG;

CREATE TABLE USUARIO(
ID INT IDENTITY PRIMARY KEY 
,EMAIL VARCHAR(250) NOT NULL UNIQUE 
,SENHA VARCHAR(250) NOT NULL
,TIPO_USUARIO VARCHAR(250) NOT NULL
);

CREATE TABLE GRUPO(
ID INT IDENTITY PRIMARY KEY
,NOME_GRUPO VARCHAR(250) NOT NULL UNIQUE 
);

CREATE TABLE PROFESSOR(
ID INT IDENTITY PRIMARY KEY
,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID)
,NOME_PROFESSOR VARCHAR(250) NOT NULL
,ID_GRUPO INT FOREIGN KEY REFERENCES GRUPO(ID)
);

CREATE TABLE PROJETOS(
ID INT IDENTITY PRIMARY KEY 
,NOME_PROJETO VARCHAR(250) NOT NULL UNIQUE 
,DESCRICAO VARCHAR(250) NOT NULL
,TEMA VARCHAR(250) NOT NULL 
,ID_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSOR(ID)
,SITUACAO INT NOT NULL
);

